config/routes.rb
require 'api_constraint'
Rails.application.routes.draw do
  resources :api_keys,  :except => [:edit, :update]
  # namespace :api, defaults: { format: :json },
  #                              constraints: { subdomain: 'api' }, path: '/'  do
  #   scope module: :v1, constraints: ApiConstraint.new(version: 1, default: true) do
      match '/find_duplicates', to: 'api_keys#find_duplicates', via: [:get, :post]#, on: :collection
    # end
    # end
  root to: 'api_keys#index'
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  validates_presence_of :email
  validates :email, email_format: { message: "is not valid" }

  # Return the object with words and reapeted indexes
  def get_duplicates(array)
    array.each_with_index.group_by{|f,i| f}.each{|k,v| v.map!(&:last)}
    .map { |i,a| {word: i, positions: a} if (a.length >1) }.compact
  end

 # Set the counter for eache request
  def set_requests
    self.update_attribute('requests', self.requests + 1);
  end

  # Return the object  get it from get duplicates
  def find_by_key(data)
    self.set_requests
    return self.get_duplicates(data)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/api/v1/api_keys_controller.rb
Class Api::V1::ApiKeysController < Api::V1::BaseController

  # #GET /api/v1/find_duplicates
  # #GET /api/v1/find_duplicates.json
  def find_duplicates
    binding.pry
    @api_key = ApiKey.find_by(api_key: params[:api_key])
    @data = params[:data]
    respond_to do |format|
      if @api_key.blank?
        format.json { render json: {code: '401', status: :unauthorized}, status: :unauthorized }
        format.html { redirect_to api_keys_path, status: :unauthorized }
      else
        @duplicates = @api_key.get_duplicates(@data)
        @api_key.set_requests
        format.json { render json: {code: '200', status: :success, duplicates: @duplicates}, status: :ok}
      end
    end
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def not_found
    return api_error(status: 404, errors: 'Not found')
  end

  def unauthenticated!
    api_error(status: 401, errors: 'unauthorized')
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  # move API-specific filters/logic from ApplicationController to here
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :set_api_key, only: [:show, :edit, :update, :destroy]
  before_action :set_md5_api_key, only: [:create, :update]
  before_action :get_api_key, only: :find_duplicates

  # GET /api_keys
  # GET /api_keys.json
  def index
    @api_keys = ApiKey.all
  end

  # GET /api_keys/1
  # GET /api_keys/1.json
  def show
  end

  # GET /api_keys/new
  def new
    @api_key = ApiKey.new
  end

  # GET /api_keys/1/edit
  def edit
  end

  # POST /api_keys
  # POST /api_keys.json
  def create
    @api_key = ApiKey.new(api_key_params)
    respond_to do |format|
      if @api_key.save
        format.html { redirect_to @api_key, notice: 'Api key was successfully created.' }
        format.json { render :show, status: :created, location: @api_key }
      else
        format.html { render :new }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api_keys/1
  # PATCH/PUT /api_keys/1.json
  def update
    respond_to do |format|
      if @api_key.update(api_key_params)
        format.html { redirect_to @api_key, notice: 'Api key was successfully updated.' }
        format.json { render :show, status: :ok, location: @api_key }
      else
        format.html { render :edit }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_keys/1
  # DELETE /api_keys/1.json
  def destroy
    @api_key.destroy
    respond_to do |format|
      format.html { redirect_to api_keys_url, notice: 'Api key was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def find_duplicates
      if @duplicates.blank?
         render json: {code: '401', status: :unauthorized}, status: :unauthorized
        # format.html { redirect_to api_keys_path, status: :unauthorized }
      else
        render json: {code: '200', status: :success, duplicates: @duplicates}, status: :ok
      end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_api_key
    @api_key = ApiKey.find(params[:id])
  end

  #Use Digest to set the api_key parameter
  def set_md5_api_key
    email =   params[:api_key][:email]
    params[:api_key][:api_key] = Digest::MD5.hexdigest(email) unless email.blank?
  end

  #get the params for call the method to search the result duplicates
  def get_api_key
    @api_key = ApiKey.find_by(api_key: params[:api_key])
    @data = params[:data]
    #  @api_key = ApiKey.first
    # @data = ["hola","parso","mundo","hola","agua","papa","parso"]
    @duplicates = @api_key.find_by_key(@data)  unless @api_key.blank?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def api_key_params
    params.require(:api_key).permit(:email, :api_key, :requests, :data)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_keys/_form.html.erb
<%= form_with(model: api_key, local: true, class: "form-horizontal") do |form| %>
  <% if api_key.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(api_key.errors.count, "error") %> prohibited this api_key from being saved:</h2>
      </div>
      <ul>
      <% api_key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6">
     <div class="form-group field">
        <%= form.label :email, class: "control-label" %>
        <%= form.text_field :email, { id: :api_key_string, type: "email", class: "form-control",placeholder:"Insert an email", autofocus: "autofocus"} %>
    </div>
    <div class="form-group actions">
      <%= link_to (root_path), class: "btn btn-sm btn-default", role: "button"   do %><span class="glyphicon glyphicon-chevron-left"></span> Back<%end%>
      <%= form.submit "New api Key", class: "btn btn-sm btn-primary"%>
    </div>
  </div>
<% end %>

app/views/api_keys/edit.html.erb
<h1>Editing Api Key</h1>

<%= render 'form', api_key: @api_key %>

<%= link_to 'Show', @api_key %> |
<%= link_to 'Back', api_keys_path %>

app/views/api_keys/index.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>
    <h1 class="center">Api Keys</h1>
    <div class="col-md-10">
      <table class="table table-responsive table-condensed">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Email</th>
            <th scope="col">Api Key</th>
            <th scope="col">Num of Requests</th>
            <th scope="col" colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @api_keys.each do |api_key| %>
            <tr>
              <td><%= api_key.email %></td>
              <td><%= api_key.api_key %></td>
              <td><%= api_key.requests %></td>
              <td><%#= link_to 'Show', api_key %></td>
              <td><%= link_to 'Delete', api_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'New Api Key', new_api_key_path ,class: 'btn btn-primary btn-sm' %>
    </div>

  </div>
</div>

app/views/api_keys/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Generate a new Api Key</h1>
    <%= render 'form', api_key: @api_key %>
  </div>
</div>

app/views/api_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @api_key.email %>
</p>

<p>
  <strong>Api Key:</strong>
  <%= @api_key.api_key %>
</p>

<p>
  <strong>Num of requests:</strong>
  <%= @api_key.requests %>
</p>

<%= link_to 'Back', api_keys_path, class: 'btn btn-sm btn-default', role: 'button' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParsoApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>